### ISSUE TITLE
"Remember me" Login not working

### ISSUE THREAD

**Issue by brenopolanski** [hugopl/reviewit#106]
Not is possible to remember the users’ login state.

![screenshot from 2017-02-21 10-14-19](https://cloud.githubusercontent.com/assets/1894191/23166267/bd15390e-f81e-11e6-8ff0-aa59cfb7efbf.png)

**Comment by hugopl** [comment]
This seems a devise behavior, i.e. it doesn't store this checkbox status anywhere, but uses its value when doing the user login.

**Comment by hugopl** [comment]
here's more info: http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Rememberable

So I'll close this as invalid, wontfix, whatever :-), Thanks!
