### ISSUE TITLE
Implement web push notification

### ISSUE THREAD

**Issue by hugopl** [hugopl/reviewit#108]
That's it, web push notifications... for all MR events.

**Comment by brenopolanski** [comment]
Notify other devices for all MR events ??

Another option would sending the notification using [Pushbullet](https://www.pushbullet.com/). People would have to create an account, get a token and the app.

Maybe is an interesting feature :)

**Comment by hugopl** [comment]
Done in commits:
cd0a7b880bd72500ce6b0bc35e2fff1bd4c7c37b
c858d4cb137bf0eeaf3443eaa17adc271cdcd87b
dc290a59b54e2a7eb49cb837c9220cb0b6cf8bf0
8a2a19841857e3014eeaa2e2ebfd754055b86011
2245cd6ebd5c51e7a715deb2666f11f9b82350e0
1c34c121588a3972e7a70000837087a01439b71a
fdf2cb87b5678797e11f8eba7380ecae06a981e4
ae954f0d20c855ed0fd267b90a9b67cc32b0e7b6
