### ISSUE TITLE
Notify other devices for all MR events

### ISSUE THREAD

**Issue by brenopolanski** [hugopl/reviewit#109]
Another option would sending the notification using [Pushbullet](https://www.pushbullet.com/). People would have to create an account, get a token and the app.

Maybe is an interesting feature :)

**Comment by hugopl** [comment]
reviewit is a dev tool, so usually people using it are on desktop, not mobile (BTW it sux on mobile), this may be a useful feature, however register on another site to have the service seems no the way to go IMO.

**Comment by brenopolanski** [comment]
Yeah.. make sense!!
Maybe for now this feature is not valid as devs use the application on the desktop.
