### ISSUE TITLE
Your projects: "see merge requests" link is displayed even when there isn't MRs to be displayed.

### ISSUE THREAD

**Issue by edmilsonefs** [hugopl/reviewit#11]
**Problem**: An user action that does not give anything valuable.

**Possible solutions**:
1. Add a simple check to only display this link if we have at least one MR. (easier solution)
2. Implement a counter to display how many MR are pending and closed for each project. If it doesn't have a merge request, make it a plain text instead of a link.

**An example**(something like that):
* Project A, [5 Pending](link 01) and 0 Closed merge request(s).
* Project B, 0 Pending and [6 Closed](link 02) merge request(s).

**Comment by edmilsonefs** [comment]
![screenshot_012715_125731_am](https://cloud.githubusercontent.com/assets/498938/5913640/5931da3e-a5c6-11e4-9673-b2c7694279df.jpg)

**Comment by hugopl** [comment]
It's not worth to add a link to closed merge requests since in practice you rarely need to see the closed merge requests list. however see how much pending merge requests exists seems more useful.

**Comment by edmilsonefs** [comment]
Makes sense.

**Comment by hugopl** [comment]
Fixed in commit 0f0d5fefbe51e723b825fb0e7ac7b86b30dd9524.
