### ISSUE TITLE
Add a flag on CLI to enable MR creation on a dirty working copy.

### ISSUE THREAD

**Issue by hugopl** [hugopl/reviewit#115]
The CLI by default check if the working copy is dirty, because forgetting to `git add` a file is a common mistake among developers, however some times we want to push something knowing our working copy is dirty. So this is about to create a flag to allow that.

**Comment by smithascari** [comment]
Maybe prompting us when working copy is dirty would be better, and we don't need any extra config.

**Comment by hugopl** [comment]
Implemented in commit d6546afc53ba437fd485dca03989907aa2f8537b
