### ISSUE TITLE
Keep comments on unchanged lines between reviews

### ISSUE THREAD

**Issue by smithascari** [hugopl/reviewit#116]
It's common to forgot about some comments between versions. It should keep comments for unchanged lines when a new version of MR is submitted

**Comment by hugopl** [comment]
I have some ideas about how to do a review and keep track of comments and change requests... in a way not too complicated like in github and not too feature-less as it is now.

**Comment by hugopl** [comment]
With the new comment blockers, this feature isn't needed anymore.

**Comment by hugopl** [comment]
here's the related patch I said: e8ab71f4e0fe8fc37c80a4f80df5779f475c0654
