### ISSUE TITLE
Add visual identification for the labels of the required fields.

### ISSUE THREAD

**Issue by edmilsonefs** [hugopl/reviewit#12]
**Problem**: Is not clear which fields are required. _(usability)_

**Comment by edmilsonefs** [comment]
![screenshot_012715_014845_am](https://cloud.githubusercontent.com/assets/498938/5913658/a324a1bc-a5c6-11e4-8d3e-be5b4b669e03.jpg)

**Comment by hugopl** [comment]
Fixed in commit d8e9b89002712fbe8d619f0d21f177001050e754.
