### ISSUE TITLE
Anchor comments on reviews

### ISSUE THREAD

**Issue by arthurgouveia** [hugopl/reviewit#57]
Would be great to have the ability of anchoring directly to the comment and/or line of code by having these with specific ID's on the DOM, like

https://reviewit.mycompany.com/projects/1/merge_requests/478#line-1257
or
https://reviewit.mycompany.com/projects/1/merge_requests/478#comment-1257

**Comment by hugopl** [comment]
Fixed in commit 9ba8fbe411892982351e60df1fa125ec917065ce.
