### ISSUE TITLE
Mark MR as approved but do not accept

### ISSUE THREAD

**Issue by sergiopvilar** [hugopl/reviewit#85]
With the feature introduced in #66 will be great if we had the ability to approve a MR when there's more than one reviewer but not properly accept it. The purpose of this feature is to give an approval to the people that will merge the MR. We can also introduce an option that the MR only can be merged when all reviewers give the approval.

**Comment by hugopl** [comment]
I think it's better to implement this as a specific way to say +1 to the MR.

**Comment by hugopl** [comment]
implemented :-)
