### ISSUE TITLE
Delete users should not destroy any database entries

### ISSUE THREAD

**Issue by hugopl** [hugopl/reviewit#9]
Delete users should not destroy the database entries, but just disable the users, so we keep the history, i.e. user comments, etc...

**Comment by edmilsonefs** [comment]
**Proposed solution**:
1. Add a boolean flag in the user table.
2. Add a filter that only lists content that comes from active users.

Do you think this is enough to solve this issue?

**Comment by rimenes** [comment]
What's the desired behavior if the user wishes to use the app again: re-enable his current account or create a new account?

**Comment by hugopl** [comment]
I think just re-enable the account, but for a first version we can ignore this use case.

**Comment by edmilsonefs** [comment]
When I looked on this issue what I thought it was is that instead of delete the user, we  create a boolean/flag column to turn it on or off and after that just update the views files to filter by this flag. (maybe the easiest way to handle that)

**Comment by edmilsonefs** [comment]
@hugopl and what do you think to permits the password reset in a meanwhile be used to re-enable the inactive accounts? The old data will be ordered normally, the newer MR will be at the top in a chronological order, the rest the pagination will take care. This way it will be fully functional but at least less complex.

**Comment by hugopl** [comment]
Fixed in commit 4ce38c78b2e6371e6ebe24a057f795bc4e63ac1e.
